//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MauIn()
        {
            this.LichSuIns = new HashSet<LichSuIn>();
        }
    
        public int id { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public Nullable<System.Guid> fileMau { get; set; }
        public byte[] anhMauIn { get; set; }
        public string fileID { get; set; }
        public string price { get; set; }
        public byte[] ContentFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuIn> LichSuIns { get; set; }
    }
}
