//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int maMay { get; set; }
        public string TenMay { get; set; }
        public Nullable<int> soGiayHienTai { get; set; }
        public byte[] anh { get; set; }
    }
}
