//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID
    {
        public int id { get; set; }
        public string rfid1 { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> userInfo { get; set; }
    
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
