//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.DiscountCodes = new HashSet<DiscountCode>();
            this.LichSuIns = new HashSet<LichSuIn>();
            this.RFIDs = new HashSet<RFID>();
        }
    
        public int STT { get; set; }
        public string TenNguoiDung { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> khoa { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string ghiChu { get; set; }
        public string SDT { get; set; }
        public byte[] anh { get; set; }
        public Nullable<int> gioiTinh { get; set; }
        public string diaChi { get; set; }
        public string khoaString { get; set; }
        public string password { get; set; }
        public Nullable<bool> kichHoat { get; set; }
        public string gioiTinhString { get; set; }
        public string theThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCode> DiscountCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuIn> LichSuIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFID> RFIDs { get; set; }
    }
}
